
from incidents import insertIncidents
import json
import datetime
ADDR_STATE= {
    "New York, NY" :"NY",
    "Philadelphia, PA" :"PA",
    "Boston, MA" :"MA",
    "Los Angeles, CA" :"CA",
    "San Fernando Valley, CA" :"CA",
    "Plymouth, IN" :"IN",
    "Azusa, CA" :"CA",
    "San Francisco, CA" :"CA",
    "Oceanside, CA" :"CA",
    "Brooklyn, NY" :"NY",
    "Burbank, CA" :"CA",
    "Garden Grove, CA" :"CA",
    "Fresno, CA" :"CA",
    "Albuquerque, NM" :"NM",
    "Campton, CA" :"CA",
    "Queens, NY" :"NY",
    "Midland, TX" :"TX",
    "Kirkland, WA" :"WA",
    "Redmond, WA" :"WA",
    "Anaheim, CA" :"CA",
    "Miami Beach, FL" :"FL",
    "Charlottesville, VA" :"VA",
    "Ithaca, NY" :"NY",
    "Daly City, CA" :"CA",
    "Louisville, KY" :"KY",
    "San Diego, CA" :"CA",
    "Seattle, WA" :"WA",
    "Madison, WI" :"WI",
    "Dallas, TX" :"TX",
    "Toronto, Ont." :"BAD",
    "Orange, CA" :"CA",
    "New York" :"NY",
    "South St. Paul, MI" :"MI",
    "Bronx, New York" :"NY",
    "Houston, TX" :"TX",
    "Fullerton, CA" :"CA",
    "Omaha, Nebraska" :"NB",
    "Louisville, CO" :"CO",
    "Denver, CO" :"CO",
    "Yakima, WA" :"WA",
    "Martinsville, IN" :"IN",
    "Woodbury, MN" :"MN",
    "Bronx, NY" :"NY",
    "SAN ANGELO, TX" :"TX",
    "Milwaukee, WI" :"WI",
    "Miami, FL" :"FL",
    "Fort Smith, AR" :"AR",
    "Luna County, NM" :"NM",
    "Detroit, Michigan" :"MI",
    "ALBUQUERQUE, N.M." :"NM",
    "Watertown, Massachusetts" :"MA",
    "Westchester, NY" :"NY",
    "Reno, NV" :"NV",
    "Berkeley, CA" :"CA",
    "Vancouver, WA" :"WA",
    "Detroit, MI" :"MI",
    "Seymour, CT" :"CT",
    "Pittsburgh, PA" :"PA",
    "Amherst, MA" :"MA",
    "Bellevue, Washington" :"WA",
    "Santa Monica, CA" :"CA",
    "Green Bay, WI" :"WI",
    "Pasadena, CA" :"CA",
    "Napervill, Ill" :"IL",
    "Davie, FL" :"FL",
    "South Bend, IN" :"IN",
    "Vestal, NY" :"NY",
    "Washington DC" :"DC",
    "Syracuse, NY" :"NY",
    "North Carolina" :"NA",
    "Sacramento, CA" :"CA",
    "Anahiem, CA" :"CA",
    "Edison, NJ" :"NJ",
    "Seatttle, WA" :"WA",
    "Newton, MA" :"MA",
    "Sunnyvale, CA" :"CA",
    "Toronto, ON" :"ON",
    "Philadelphia, PA (University City)" :"PA",
    "Philadelphia, PA (South Philly)" :"PA",
    "Philadelphia, PA (Fairmount)" :"PA",
    "Cherry Hill, NJ" :"NJ",
    "San Angelo, TX" :"TX",
    "Louisiana" :"LA",
    "San Jose, California" :"CA",
    "Huntington Beach, CA" :"CA",
    "Atlanta, Georgia" :"GA",
    "Vancouver, Canada" :"BAD",
    "Washington, DC" :"DC",
    "Pasedena, CA" :"CA",
    "Arkansas" :"AK",
    "San Franciso, CA" :"CA",
    "San Antonio, TX" :"TX",
    "Delaware" :"DE",
    "Florida" :"FL",
    "Des Moines, Iowa" :"IW",
    "Harlem, NY" :"NY",
    "Washington, D.C." :"DC",
    "New York, NY (Lexington and 59th)" :"NY",
    "Hoboken, NJ" :"NJ",
    "Chesapeake, VA" :"VA",
    "Hayward, CA" :"CA",
    "Vancouver, BC, Canada" :"BAD",
    "St. Paul, MN" :"MN",
    "Baker, CA" :"CA",
    "Manhattan, NY 10003" :"NY",
    "Lakewood, Ohio (Detroit Ave)" :"OH",
    "Columbus, Ohio (Downtown)" :"OH",
    "Raleigh, North Carolina" :"NC",
    "Overland Park, Kansas" :"KS",
    "Texas" :"TA",
    "St. Paul, Minnesota" :"MN",
    "Austin, Texas (North)" :"TA",
    "Vancouver, BC, CAN (Waterfront Station)" :"BAD",
    "Vancouver, BC, CAN ( Columbia Street)" :"BAD",
    "Vancouver, BC, CAN (Downtown)" :"BAD",
    "Montreal, QB, CAN (Longueil Maxi)" :"BAD",
    "Montreal, QB, CAN (Cote-des-Neiges)" :"BAD",
    # "Montreal, QB, CAN (D carie Boulevard near Sherbrooke Street)" :"BAD",
    "Nunavik, QB, CAN" :"BAD",
    "Tornoto, CAN (University Avenue and Adelaide Street West )" :"BAD",
    "Stockton, CA" :"CA",
    "San Antonio,TX" :"TX",
    "Eureka, Missouri" :"MO",
    "Vancouver, BC, CAN ( Main and East Hastings)" :"BAD",
    "San Luis Obispo, CA" :"CA",
    "Seattle, WA (Sodo)" :"WA",
    "Southern California" :"SC",
    "Stevens Point, Wisconsin" :"WI",
    "Alameda County, CA" :"CA",
    "Saskatoon, Saskatchewan, CAN" :"BAD",
    "Tenderloin, San Francisco, CA" :"CA",
    "Bayside, Queens, NY" :"NY",
    "Downtown Seattle, WA" :"WA",
    "Golden Gardens Park, Seattle, WA" :"WA",
    "2000 block of Northwest Market Street, Seattle, WA" :"WA",
    "Myrtle Beach, SC" :"SC",
    "Renton, WA" :"WA",
    "Omaha, NE" :"NE",
    "Rialto, CA" :"CA",
    "Bay Ridge, NY" :"NY",
    "1600 Pennsylvania Ave NW, Washington, DC 20500" :"DC",
    "219 E 188th St, The Bronx, NY 10458" :"NY",
    "Jacksonville, FL" :"FL",
    "Torrance, CA" :"CA",
    "Hair & Wig Beauty Supply\n139 Central Ave, Albany, NY 12206" :"NY",
    "Almaden, CA" :"CA",
    "85 Crescent Ave #5, Wyckoff, NJ 07481" :"NJ",
    "Kelowna, British Columbia, Canada" :"BAD",
    "227 Don Gaspar Ave, Santa Fe, NM 87501" :"NM",
    "University of Delaware, Newark, DE 19716" :"DE",
    "415 W Carmel Valley Rd, Carmel Valley, CA 93924" :"CA",
    "Marin County, CA" :"CA",
    "155 Walnut Ave, Santa Cruz, CA 95060" :"CA",
    "16th Ave. and 77th St., Bensonhurst, NY" :"NY",
    "7423 Fair Oaks Blvd, Carmichael, CA 95608" :"CA",
    "2545 Research Blvd, Fort Collins, CO 80526" :"CO",
    "Edmonton, Canada" :"BAD",
    "3676 St Clair Ave E, Scarborough, ON M1M 1T2, Canada" :"BAD",
    "42nd Street and 6th Avenue, New York, NY" :"NY",
    "Fanwood, NJ" :"NJ",
    "Davis, CA" :"CA",
    "715 Central Pkwy W, Mississauga, ON L5B 4L1, Canada" :"BAD",
    "Los Altos, CA" :"CA",
    "White Lake Township, MI" :"MI",
    "Seymour Street and Pender Street, Vancouver, Canada" :"BAD",
    "360 Hollywood Ave, North York, ON M2N 3L4, Canada" :"BAD",
    "7th Ave. 58th St. Brooklyn, NY" :"NY",
    "Baltimore, MD" :"MD",
    "4801 Victoria Dr, Vancouver, BC V5P 4P3, Canada" :"BAD",
    "1104 Hoover St, Los Angeles, CA 90006" :"CA",
    "Plano, TX" :"TX",
    "Pompano Beach, FL" :"FL",
    "2676 Fairway Hills Rd #6, Blind Bay, BC V0E 1H2, Canada" :"BAD",
    "13th and Walnut Street, Philadelphia, PA" :"PA",
    "Melrose, Bronx, NY" :"NY",
    "Anza Vista, San Francisco, CA" :"CA",
    "Oakland, CA" :"CA",
    "10300 Little Patuxent Pkwy, Columbia, MD 21044" :"MD",
    "2401 W Valley Blvd, Alhambra, CA 91803" :"CA",
    "418 S 2nd St, San Jose, CA 95113" :"CA",
    "First Avenue and 14th Street, NYC, NY" :"NY",
    "52 Waller St, San Francisco, CA 94102" :"CA",
    "N Lombard TC MAX Station, Portland, OR 97217" :"OR",
    "Portland, OR" :"OR",
    "2738 SE 82nd Ave #203b, Portland, OR 97266" :"OR",
    "International Blvd & 6th Ave\nOakland, CA 94606" :"CA",
    "812 S Central Ave, Medford, OR 97501" :"OR",
    "555 Red Lion Rd, Huntingdon Valley, PA 19006" :"PA",
    "340 6th Ave, New York, NY 10011" :"NY",
    "57th Street subway, New York, NY 10019" :"NY",
    "W 125th St & St Nicholas Ave, New York, NY 10027" :"NY",
    "Encanto/62nd St Trolley Stn, San Diego, CA 92114" :"CA",
    "West 4th St station, New York, NY 10012" :"NY",
    "2101 P St NW, Washington, DC 20037" :"DC",
    "56 Ross Alley, San Francisco, CA 94108" :"CA",
    "135 St station, New York, NY 10030" :"NY",
    "Sunset District, San Francisco, CA" :"CA",
    "Japantown, San Jose, CA 95112" :"CA",
    "1840 Sutter St, San Francisco, CA 94115" :"CA",
    "8973 Grant Line Rd #100, Elk Grove, CA 95624" :"CA",
    "31st St & Broadway, Queens, NY 11106" :"NY",
    "600 El Capitan Dr, Danville, CA 94526" :"CA",
    "60 Thompson St, Fairfield, CT 06824" :"CT",
    "1605 Juan Tabo Blvd NE, Albuquerque, NM 87112" :"NM",
    "Montana Ave & Bundy Dr, Los Angeles, CA 90049" :"CA",
    "1400 2nd Ave, New York, NY 10021" :"NY",
    "2961 El Camino Real, Tustin, CA 92782" :"CA",
    "Netflix 100 Winchester Circle, Los Gatos, CA, 95032" :"CA",
    "4425 La Jolla Village Dr, San Diego, CA 92122" :"CA",
    "3646 California Rd, Orchard Park, NY 14127" :"NY",
    "Lancaster Hwy, Pineville, NC" :"NC",
    "318 Sip Ave, Jersey City, NJ 07306" :"NJ",
    "ONLINE" :"BAD",
    "Avenida De La Playa, San Diego, CA 92037" :"CA",
    "3602 36th Ave, Astoria, NY 11106" :"NY",
    "1 Terminal Dr, Kenner, LA 70062" :"LA",
    "4419 18th Ave, Brooklyn, NY 11204" :"NY",
    "Fremont, CA" :"CA",
    "ONLINE - Twentynine Palms, CA" :"CA",
    "6th St NW & Pennsylvania Avenue NW, Washington, DC 20004" :"DC",
    "Austin, MN" :"MN",
    "21 Mile Road, Macomb, MI 48042" :"MI"
}

def loadData(fileName):
    incidents = []
    with open(fileName) as f:
        data = json.load(f)
        for item in data:
            '''
            "attributes": {
                            "Date_of_incident": "2/5/2020",
                            "Place_of_Incident": "New York, NY",
                            "Summary": "A woman wearing a face mask was punched and kicked by a man who called her \"diseased\".",
                            "News_Source": "https://www.nbcnews.com/news/us-news/coronavirus-hate-attack-woman-face-mask-allegedly-assaulted-man-who-n1130671?cid=sm_npd_nn_tw_ma",
                            "Latitude": 40.718353,
                            "Longitude": -73.993869,
                            "__OBJECTID": 0
                        }
            '''         
            record = item.get("attributes")
            if  not record.get("Place_of_Incident") in ADDR_STATE or "BAD" == ADDR_STATE[record.get("Place_of_Incident")]:
                continue
            try:
                incidents.append(dict(
                    incident_time=datetime.datetime.strptime(record.get("Date_of_incident"), '%m/%d/%Y'),
                    created_on=datetime.datetime.now(),
                    incident_location=ADDR_STATE[record.get("Place_of_Incident")],
                    abstract=record.get("Summary"),
                    url=record.get("News_Source"),
                    incident_source="racismiscontagious",
                    title=record.get("Summary")               
                ))
            except Exception as e:
                print(e)
    insertIncidents(incidents)

